/**
 * 构建「骨架」数据集 —— 仅生成全部 700 字 + 拼音，不调用 OpenAI、不生成故事和插画。
 *
 * 用途：
 *   1. 第一次拉代码，没填 OpenAI Key，也能在 App 里浏览全部字表（一上/一下/搜索）。
 *   2. 后续再跑 `npm run build:dataset` 时，会原地补齐故事和插画。
 *
 * 运行：
 *   npm run build:skeleton
 *
 * 输出：
 *   - assets/data/characters.json   （含 697 字 + 拼音；故事为空字符串；image 字段为空）
 *   - src/data/imageMap.ts          （空 map，留待 build-dataset 后填充）
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { allChars, getVolumeOf } from './wordlist';
import { getCharPinyin, annotateText } from './generate-pinyin';
import type { Character } from '../src/types';

const PROJECT_ROOT = path.resolve(__dirname, '..');
const DATA_OUT = path.join(PROJECT_ROOT, 'assets/data/characters.json');
const IMAGE_MAP_OUT = path.join(PROJECT_ROOT, 'src/data/imageMap.ts');

function loadExistingDataset(): Record<string, Character> {
  if (!fs.existsSync(DATA_OUT)) return {};
  try {
    const raw = JSON.parse(fs.readFileSync(DATA_OUT, 'utf8'));
    const map: Record<string, Character> = {};
    for (const c of raw.characters || []) {
      map[c.char] = c;
    }
    return map;
  } catch {
    return {};
  }
}

function buildSkeleton(): Character[] {
  const existing = loadExistingDataset();
  return allChars.map((char): Character => {
    const prior = existing[char];
    const pinyin = prior?.pinyin || getCharPinyin(char) || '';
    return {
      char,
      pinyin,
      volume: getVolumeOf(char),
      story: prior?.story && prior.story.text
        ? prior.story
        : { text: '', annotated: annotateText(char) }, // 留空，等 build-dataset 填
      image: prior?.image || '',
    };
  });
}

function writeImageMapPlaceholder() {
  const lines = [
    '// AUTO-GENERATED by scripts/build-dataset.ts / scripts/build-skeleton.ts',
    '// DO NOT EDIT BY HAND.',
    '',
    'const map: Record<string, any> = {',
    '  // 运行 `npm run build:dataset` 后会在这里插入所有图片的 require 行',
    '};',
    '',
    'export function getImageFor(char: string): any | null {',
    '  return Object.prototype.hasOwnProperty.call(map, char) ? map[char] : null;',
    '}',
    '',
  ];
  fs.writeFileSync(IMAGE_MAP_OUT, lines.join('\n'), 'utf8');
}

function main() {
  const characters = buildSkeleton();
  const payload = {
    version: '0.1.0-skeleton',
    generatedAt: new Date().toISOString(),
    characters,
  };
  fs.mkdirSync(path.dirname(DATA_OUT), { recursive: true });
  fs.writeFileSync(DATA_OUT, JSON.stringify(payload, null, 2), 'utf8');

  // 只在 imageMap.ts 还不存在或当前为空时才覆盖（避免冲掉 build-dataset 写入的真实 map）
  const imageMapExists = fs.existsSync(IMAGE_MAP_OUT);
  const imageMapContent = imageMapExists ? fs.readFileSync(IMAGE_MAP_OUT, 'utf8') : '';
  const hasRealRequires = /require\(/.test(imageMapContent);
  if (!hasRealRequires) {
    writeImageMapPlaceholder();
  }

  console.log(`✅ 已写入 ${characters.length} 个字到 ${path.relative(PROJECT_ROOT, DATA_OUT)}`);
  console.log(`   一上: ${characters.filter(c => c.volume === 'upper').length} 字`);
  console.log(`   一下: ${characters.filter(c => c.volume === 'lower').length} 字`);
  console.log('');
  console.log('💡 下一步：填好 .env 里的 OPENAI_API_KEY 后运行 `npm run build:dataset` 补齐故事和插画。');
}

main();
